title: P4
description: P4 Web Portal
baseURL: http://localhost:9000
publishDir: ./dev

pluralizeListTitles: false
capitalizeListTitles: false

timeZone: Europe/Rome
defaultContentLanguage: it
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true

minify: false
disableKinds:
  - sitemap
  - robotsTXT
  - RSS
