it:
  languageCode: it-IT
  languageName: Italiano
  title: TMP-4
  weight: 1
  menus:
    main:
      - name: modello concettuale
        pageRef: /book
        weight: 1
      - name: conosci te stesso
        pageRef: /kts
        weight: 2
      - name: fai match
        pageRef: /match
        weight: 3
      - name: credits
        pageRef: /credits
        weight: 4
en:
  disabled: True
  languageCode: en-US
  languageName: English
  title: TMP-4
  weight: 2
  menus:
    main:
      - name: conceptual framework
        pageRef: /book
        weight: 1
      - name: know yourself
        pageRef: /kts
        weight: 2
      - name: make a match
        pageRef: /match
        weight: 3
      - name: credits
        pageRef: /credits
        weight: 4
